---
- name: apt update
  apt:
    update_cache: yes
- name: Check for mc
  apt:
    name: mc
    state: latest
- name: Check for rsync
  apt:
    name: rsync
    state: latest
- name: Uninstall nginx
  apt:
    name: nginx
    state: absent
